### ISSUE TITLE
preg_match(): Compilation failed: missing closing parenthesis at offset 4 - HTML.php on line 180

### ISSUE THREAD

**Issue by jcatello** [wp-media/wp-rocket#4379]
**Describe the bug**

When upgrading to 3.9.4 the following starts spamming the PHP errors logs:

`PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 4 in /home/nginx/domains/domain.com/public/wp-content/plugins/wp-rocket/inc/Engine/Optimization/DelayJS/HTML.php on line 180`

Rolling back to a previous version, in our case, was 3.8.8 has fixed it.

**Comment by piotrbak** [comment]
Hello @jcatello thanks for being in touch. This case is already reported here:
https://github.com/wp-media/wp-rocket/issues/4136
and a similar one here:
https://github.com/wp-media/wp-rocket/issues/3967

If you want to use 3.9+ version of WP Rocket without warnings, you'll need to find a different exclusion pattern than the one that doesn't have closing parenthesis (or escape the parenthesis with`\`, for example `\(` as stated in the [doc](https://docs.wp-rocket.me/article/1492-google-analytics-google-ads-tracking-issues)), until we fix this problem.
